### ISSUE TITLE
Custom error messages 

### ISSUE THREAD

**Issue by rgmax** [acavestro/hapi-attempts-limiter#1]
It will be great if we can set custom global error message. For example:
```javascript
server.register({
  register: require('hapi-attempts-limiter'),
  options: {
    namespace: 'FOO',
    redisClient: yourRedisInstance
    errorMessage: Boom.create(429, 'your customized message')
    global: {
      limit: 5,
      duration: 60
    }
  }
});
```

**Comment by acavestro** [comment]
Hi @rgmax thanks for your feedback!

As soon as my team will schedule some time to work on the plugin, I'm sure I'll implement this feature! Just give me some time :)

**Comment by acavestro** [comment]
Added in v1.4.0 (99853d0fcc942de4cedec8fbf759935d9464e008)
